# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Proc-JobQueue
version:      0.3
version_from: lib/Proc/JobQueue.pm
installdirs:  site
requires:
    aliased:                       0
    Callback:                      0
    Eval::LineNumbers:             0
    File::Slurp:                   0
    File::Slurp::Remote::BrokenDNS: 0
    File::Temp:                    0
    Hash::Util:                    0
    Proc::Background:              0
    RPC::ToWorker:                 0
    Scalar::Util:                  0
    Tie::Function::Examples:       0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
